### ISSUE TITLE
Naming convention for counter designs

### ISSUE THREAD

**Issue by tangxifan** [tangxifan/micro_benchmark#10]
**Is your feature request related to a problem? Please describe.**
As we are enriching the counter RTL designs in https://github.com/tangxifan/micro_benchmark/tree/main/simple_registers/counters ,
it is time to establish naming convention for counters.
As such, developers can identify critical technical features from the name of a counter design.

**Describe the solution you'd like**
A naming convention could be

```
   counter[down]<size>_[async|sync]_[set|reset|setb|resetb]
```

- keyword ``down`` represent a counting down counter
- ``size`` is an integer, indicating the number of bits for a counter
- ``async`` and ``sync`` represent the feature of reset and set signal
- ``set``, ``reset``, ``setb`` and ``resetb`` indicates the existence of reset/set signal as well as polarity.

For instance,

```
counterdown8_async_resetb
```

shows a counter with the following features:

- counting down
- 8-bit in width
- Asynchronous active-low reset

**Comment by anaszameer-rs** [comment]
Just a suggestion! Wouldn't that be great if we use resetp | resetn instead of resetb to make it more clear?
For instance,
`counterdown8_async_resetp`
shows a counter with the following features:
counting down
8-bit in width
Asynchronous active-high reset

**Comment by tangxifan** [comment]
@anaszameer-rs No problem for me. We should document it. Let me start documentation template this morning. Are you o.k. to write these down in the documentation?

**Comment by tangxifan** [comment]
@anaszameer-rs If we follow the naming convention of ``p``, should we consider ``n`` for active-low signals, rather than ``b``?

**Comment by tangxifan** [comment]
@anaszameer-rs Kindly review the documentation about the naming rules at: 

https://micro-benchmark.readthedocs.io/en/latest/developer/naming_convention/#counter-design-names

If you agree, we can close this issue. The rule will be actively applied in later PRs.

**Comment by anaszameer-rs** [comment]
> ous active-high reset

@tangxifan Can we add more flexibility in counter design namings considering posedge | negedge | dual edge counters?

**Comment by tangxifan** [comment]
Good catch. Please suggest and we can update naming rules.
Currently, I will not propose to add negedge and dual edge counters massively, as OpenFPGA has not been tested on these types of counters.
But sooner or later, we should have it. Therefore, naming rules can be established now.

**Comment by anaszameer-rs** [comment]
> Good catch. Please suggest and we can update naming rules. Currently, I will not propose to add negedge and dual edge counters massively, as OpenFPGA has not been tested on these types of counters. But sooner or later, we should have it. Therefore, naming rules can be established now.

Can we add posedge | negedge | dualedge keywords for counter designs ?
for instance,
`counterdown8_posedge_async_resetn`

counting down
8-bit in width
counting on posedge of clock
Asynchronous active-low reset

**Comment by anaszameer-rs** [comment]
> > Good catch. Please suggest and we can update naming rules. Currently, I will not propose to add negedge and dual edge counters massively, as OpenFPGA has not been tested on these types of counters. But sooner or later, we should have it. Therefore, naming rules can be established now.
> 
> @tangxifan Can we add posedge | negedge | dualedge keywords for counter designs ? for instance, `counterdown8_posedge_async_resetn`
> 
> counting down 8-bit in width counting on posedge of clock Asynchronous active-low reset

@tangxifan Can you please confirm which naming convention should i follow for my upcoming PR for Counter designs ?

**Comment by tangxifan** [comment]
@anaszameer-rs Let's follow the naming convention you have proposed.
