### ISSUE TITLE
Redundant counter designs

### ISSUE THREAD

**Issue by tangxifan** [tangxifan/micro_benchmark#19]
> **Describe the bug**
> A clear and concise description of what the bug is.

Which part of the project is buggy

- [x] RTL

After merging #11 , there are some redundant counter designs which can be removed at ``simple_registers/counters/``

> **To Reproduce**
> Steps to reproduce the behavior:
> 1. Clone repository and checkout commit id: [aa7374d](https://github.com/tangxifan/micro_benchmark/commit/aa7374d4ee8d37222d6db35fb110dff43eee1510)

> **Screenshots**
![image](https://user-images.githubusercontent.com/11499826/159634320-ed1ea187-794e-4240-a6e7-85ff8efb0419.png)

**Comment by tangxifan** [comment]
@anaszameer-rs Please double check and create a PR to address this. Thanks!

**Comment by anaszameer-rs** [comment]
PR #20 resolves the issue.
