### ISSUE TITLE
dut reference argument in subroutines(async functions other than @cocotb.test)

### ISSUE THREAD

**Issue by usmanali-rs** [tangxifan/micro_benchmark#45]
> **Describe the bug**
> A clear and concise description of what the bug is.

> **To Reproduce**
> Steps to reproduce the behavior:
> 1. Deploy any `microbenchmark`'s benchmark into dv flow of `alkaid_efpga`
> 2. run the test and find the result failing
> 3. Cross check the converted testbench in dv/preconfig_cocotb/...

> **Expected behavior**
> Bitstreams should not be forced each time we call a subroutine

> **Screenshots**
> ![image](https://user-images.githubusercontent.com/91871679/195633404-51e9defc-2858-4965-8fef-62d735e1998b.png)
as you can see bitstream is forced and `dut` is used in reference, it gives object error, since `reset_dut` does not have `dut` in its scope
> **Enviornment (please complete the following information):**

>  - OS: 

- [x] Ubuntu 18.04 

>  - Tool:
 - [x] Synopsys IC Compiler

> - Version:

> **Additional context**
> Add any other context about the problem here.

**Comment by tangxifan** [comment]
@usmanali-rs Can you update your cocotb_utils to the latest? I have upgraded cocotb_utils which should already addressed this issue.

**Comment by usmanali-rs** [comment]
> @usmanali-rs Can you update your cocotb_utils to the latest? I have upgraded cocotb_utils which should already addressed this issue.

yes working on updated utils. Thanks
